document.addEventListener('DOMContentLoaded', () => {
    const startContainer = document.getElementById('start-container');
    const gameContainer = document.getElementById('game-container');
    const scrambledLettersContainer = document.getElementById('scrambled-letters');
    const dropZone = document.getElementById('drop-zone');
    const feedback = document.getElementById('feedback');
    const checkBtn = document.getElementById('check-btn');
    const nextBtn = document.getElementById('next-btn');
    const startBtn = document.getElementById('start-btn');
    const resetBtn = document.getElementById('reset-btn');
    const hintText = document.getElementById('hint-text');
    const scoreDisplay = document.getElementById('score');
    let currentTerm = {};
    let draggedTile = null;
    let score = 0;

    const scientificTerms = [
    { term: 'animal', hint: 'A living organism that can move and consume other organisms for energy.' },
    { term: 'plant', hint: 'An organism that produces its own food through photosynthesis.' },
    { term: 'organism', hint: 'Any living thing, including plants, animals, and microorganisms.' },
    { term: 'cell', hint: 'The basic structural and functional unit of all living organisms.' },
    { term: 'nucleus', hint: 'The control center of a cell that contains genetic material.' },
    { term: 'mitochondria', hint: 'Organelles that produce energy in eukaryotic cells.' },
    { term: 'chloroplast', hint: 'Organelles in plant cells where photosynthesis occurs.' },
    { term: 'stomata', hint: 'Small openings on plant leaves for gas exchange and transpiration.' },
    { term: 'photosynthesis', hint: 'The process by which plants convert sunlight into chemical energy.' },
    { term: 'respiration', hint: 'The process by which organisms break down food to release energy.' },
    { term: 'decomposer', hint: 'An organism that breaks down dead matter and recycles nutrients.' },
    { term: 'predator', hint: 'An animal that hunts and kills other animals for food.' },
    { term: 'prey', hint: 'An animal that is hunted and eaten by predators.' },
    { term: 'herbivore', hint: 'An animal that eats only plants.' },
    { term: 'carnivore', hint: 'An animal that eats only meat.' },
    { term: 'omnivore', hint: 'An animal that eats both plants and animals.' },
    { term: 'food chain', hint: 'A sequence showing how energy flows from producers to consumers.' },
    { term: 'food web', hint: 'A complex network of interconnected food chains in an ecosystem.' },
    { term: 'ecosystem', hint: 'A community of living organisms interacting with their environment.' },
    { term: 'habitat', hint: 'The natural environment where an organism lives.' },
    { term: 'adaptation', hint: 'A trait that helps an organism survive in its environment.' },
    { term: 'evolution', hint: 'The gradual change in species over time through natural selection.' },
    { term: 'species', hint: 'A group of organisms that can interbreed and produce fertile offspring.' },
    { term: 'endangered', hint: 'A species at risk of extinction due to low population numbers.' },
    { term: 'extinct', hint: 'A species that no longer exists anywhere on Earth.' },
    { term: 'biodiversity', hint: 'The variety of life forms in a given ecosystem or on Earth.' },
    { term: 'bacteria', hint: 'Single-celled microorganisms that can be beneficial or harmful.' },
    { term: 'virus', hint: 'A microscopic infectious agent that replicates inside living cells.' },
    { term: 'fungus', hint: 'A kingdom of organisms including mushrooms and yeasts that decompose matter.' },
    { term: 'algae', hint: 'Simple plant-like organisms that perform photosynthesis in water.' },
    { term: 'skeleton', hint: 'The internal framework that supports and protects the body.' },
    { term: 'bone', hint: 'A rigid organ that forms part of the skeletal system.' },
    { term: 'muscle', hint: 'Tissue that contracts to produce movement in the body.' },
    { term: 'tendon', hint: 'A tough band of fibrous tissue connecting muscle to bone.' },
    { term: 'ligament', hint: 'A band of tissue connecting bones to stabilize joints.' },
    { term: 'heart', hint: 'A muscular organ that pumps blood throughout the body.' },
    { term: 'lung', hint: 'An organ used for breathing and gas exchange in the respiratory system.' },
    { term: 'kidney', hint: 'An organ that filters waste from the blood to form urine.' },
    { term: 'liver', hint: 'An organ involved in detoxification, metabolism, and digestion.' },
    { term: 'brain', hint: 'The central organ of the nervous system that controls body functions.' },
    { term: 'nerve', hint: 'A bundle of fibers that transmits signals between the brain and body.' },
    { term: 'spine', hint: 'The vertebral column that protects the spinal cord.' },
    { term: 'blood', hint: 'A fluid tissue that transports oxygen, nutrients, and waste.' },
    { term: 'vein', hint: 'A blood vessel that carries blood back to the heart.' },
    { term: 'artery', hint: 'A blood vessel that carries blood away from the heart.' },
    { term: 'capillary', hint: 'A tiny blood vessel where exchange of substances occurs.' },
    { term: 'enzyme', hint: 'A protein that speeds up chemical reactions in the body.' },
    { term: 'protein', hint: 'A macromolecule essential for building and repairing tissues.' },
    { term: 'carbohydrate', hint: 'A macronutrient that provides quick energy for the body.' },
    { term: 'fat', hint: 'A lipid that stores energy and insulates the body.' },
    { term: 'vitamin', hint: 'An organic compound essential in small amounts for normal growth.' },
    { term: 'mineral', hint: 'An inorganic nutrient needed for body functions like bone health.' },
    { term: 'nutrient', hint: 'A substance that provides nourishment essential for growth and health.' },
    { term: 'digestion', hint: 'The process of breaking down food into absorbable nutrients.' },
    { term: 'transpiration', hint: 'The loss of water vapor from plant leaves through stomata.' },
    { term: 'root', hint: 'The part of a plant that anchors it and absorbs water and nutrients.' },
    { term: 'stem', hint: 'The main structural part of a plant that supports leaves and flowers.' },
    { term: 'leaf', hint: 'The main photosynthetic organ of a plant.' },
    { term: 'flower', hint: 'The reproductive structure of angiosperms.' },
    { term: 'seed', hint: 'A fertilized ovule containing an embryo and stored food.' },
    { term: 'fruit', hint: 'The mature ovary of a flowering plant, often containing seeds.' },
    { term: 'pollination', hint: 'The transfer of pollen from anther to stigma in flowers.' },
    { term: 'germination', hint: 'The process by which a seed sprouts and begins to grow.' },
    { term: 'reproduction', hint: 'The biological process by which new organisms are produced.' },
    { term: 'fertilization', hint: 'The fusion of gametes to form a zygote.' },
    { term: 'metamorphosis', hint: 'A dramatic change in form during an organism\'s life cycle.' },
    { term: 'larva', hint: 'The immature form of an insect that hatches from an egg.' },
    { term: 'pupa', hint: 'The life stage of some insects where metamorphosis occurs.' },
    { term: 'cocoon', hint: 'A protective case spun by some insect larvae.' },
    { term: 'chrysalis', hint: 'The hard pupal case of butterflies and moths.' },
    { term: 'molt', hint: 'The process of shedding an outer layer like skin or exoskeleton.' },
    { term: 'estivation', hint: 'A state of dormancy during hot, dry periods.' },
    { term: 'hibernation', hint: 'A state of inactivity and reduced metabolism during winter.' },
    { term: 'migration', hint: 'The seasonal movement of animals from one region to another.' },
    { term: 'territory', hint: 'An area defended by an animal against others of the same species.' },
    { term: 'instinct', hint: 'An innate, fixed pattern of behavior in animals.' },
    { term: 'behavior', hint: 'The way an organism responds to stimuli in its environment.' },
    { term: 'reflex', hint: 'An automatic, involuntary response to a stimulus.' },
    { term: 'communication', hint: 'The transfer of information between individuals.' },
    { term: 'camouflage', hint: 'Adaptation that allows an organism to blend into its surroundings.' },
    { term: 'mimicry', hint: 'When one species resembles another to gain protection.' },
    { term: 'symbiosis', hint: 'A close, long-term interaction between two different species.' },
    { term: 'parasitism', hint: 'A symbiotic relationship where one organism benefits at the other\'s expense.' },
    { term: 'mutualism', hint: 'A symbiotic relationship where both organisms benefit.' },
    { term: 'commensalism', hint: 'A symbiotic relationship where one benefits and the other is unaffected.' },
    { term: 'competition', hint: 'When organisms vie for the same limited resources.' },
    { term: 'predation', hint: 'The interaction where a predator kills and eats prey.' },
    { term: 'scavenger', hint: 'An organism that feeds on dead or decaying matter.' },
    { term: 'consumer', hint: 'An organism that eats other organisms for energy.' },
    { term: 'producer', hint: 'An organism that makes its own food through photosynthesis.' },
    { term: 'decomposition', hint: 'The breakdown of organic matter into simpler substances.' },
    { term: 'nutrient cycle', hint: 'The movement and exchange of organic and inorganic matter.' },
    { term: 'carbon cycle', hint: 'The biogeochemical cycle that describes carbon movement through ecosystems.' },
    { term: 'nitrogen cycle', hint: 'The cycle converting nitrogen between forms in the environment.' },
    { term: 'water cycle', hint: 'The continuous movement of water on, above, and below Earth\'s surface.' },
    { term: 'population', hint: 'A group of individuals of the same species in a specific area.' },
    { term: 'community', hint: 'All the populations of different species in an area.' },
    { term: 'biome', hint: 'A large community of plants and animals with similar climates.' },
    { term: 'tundra', hint: 'A cold, treeless biome with permafrost and low-growing vegetation.' },
    { term: 'taiga', hint: 'A coniferous forest biome with cold winters and short summers.' },
    { term: 'temperate forest', hint: 'A biome with moderate temperatures and four distinct seasons.' },
    { term: 'rainforest', hint: 'A warm, wet biome with high biodiversity and tall trees.' },
    { term: 'grassland', hint: 'A biome dominated by grasses with few trees.' },
    { term: 'desert', hint: 'A dry biome with very little precipitation.' },
    { term: 'savanna', hint: 'A grassland biome with scattered trees and distinct wet/dry seasons.' },
    { term: 'ocean', hint: 'The largest biome covering most of Earth\'s surface with saltwater.' },
    { term: 'coral reef', hint: 'A marine ecosystem built by calcium carbonate structures from corals.' },
    { term: 'wetland', hint: 'An area of land saturated with water, supporting aquatic plants.' },
    { term: 'chromosomes', hint: 'Thread-like structures in the nucleus carrying genetic information.' },
    { term: 'dna', hint: 'The molecule that carries genetic instructions for all living organisms.' },
    { term: 'gene', hint: 'A segment of DNA that codes for a specific protein or trait.' },
    { term: 'heredity', hint: 'The passing of traits from parents to offspring through genes.' },
    { term: 'trait', hint: 'A characteristic or feature passed from parents to offspring.' },
    { term: 'dominant', hint: 'A genetic trait that masks the effect of a recessive trait.' },
    { term: 'recessive', hint: 'A genetic trait that is expressed only when homozygous.' },
    { term: 'mutation', hint: 'A change in DNA sequence that can create genetic variation.' },
    { term: 'natural selection', hint: 'The process where organisms better adapted to their environment survive.' },
    { term: 'survival of the fittest', hint: 'The principle that well-adapted organisms are more likely to survive.' },
    { term: 'fossil', hint: 'Preserved remains or traces of ancient organisms.' },
    { term: 'paleontology', hint: 'The study of fossils to understand prehistoric life.' },
    { term: 'amber', hint: 'Fossilized tree resin that can preserve small organisms.' },
    { term: 'mold', hint: 'A fossil formed by an impression in sediment.' },
    { term: 'cast', hint: 'A fossil formed when sediment fills a mold.' },
    { term: 'imprint', hint: 'A fossilized outline or mark left by an organism.' },
    { term: 'matter', hint: 'Anything that has mass and occupies space.' },
    { term: 'mass', hint: 'The amount of matter in an object.' },
    { term: 'weight', hint: 'The force of gravity acting on an object\'s mass.' },
    { term: 'volume', hint: 'The amount of space an object occupies.' },
    { term: 'density', hint: 'Mass per unit volume of a substance.' },
    { term: 'state of matter', hint: 'The physical form of matter, such as solid, liquid, or gas.' },
    { term: 'solid', hint: 'A state of matter with definite shape and volume.' },
    { term: 'liquid', hint: 'A state of matter with definite volume but no definite shape.' },
    { term: 'gas', hint: 'A state of matter with neither definite shape nor volume.' },
    { term: 'plasma', hint: 'A state of matter consisting of ionized gas.' },
    { term: 'melting', hint: 'The change from solid to liquid state due to heat.' },
    { term: 'freezing', hint: 'The change from liquid to solid state due to cold.' },
    { term: 'boiling', hint: 'The change from liquid to gas state at boiling point.' },
    { term: 'condensation', hint: 'The change from gas to liquid state as it cools.' },
    { term: 'sublimation', hint: 'The change directly from solid to gas state.' },
    { term: 'evaporation', hint: 'The gradual change from liquid to gas below boiling point.' },
    { term: 'force', hint: 'A push or pull that can change an object\'s motion.' },
    { term: 'friction', hint: 'The force resisting motion between two surfaces in contact.' },
    { term: 'gravity', hint: 'The force that attracts objects toward each other.' },
    { term: 'magnetism', hint: 'The force exerted by magnets or magnetic fields.' },
    { term: 'magnetic field', hint: 'The region around a magnet where magnetic forces act.' },
    { term: 'magnet', hint: 'An object that produces a magnetic field.' },
    { term: 'pole', hint: 'The north or south end of a magnet where forces are strongest.' },
    { term: 'attract', hint: 'The magnetic force pulling objects together.' },
    { term: 'repel', hint: 'The magnetic force pushing like poles apart.' },
    { term: 'newton', hint: 'The SI unit of force.' },
    { term: 'acceleration', hint: 'The rate of change of velocity of an object.' },
    { term: 'velocity', hint: 'Speed in a given direction.' },
    { term: 'speed', hint: 'The rate at which an object covers distance.' },
    { term: 'motion', hint: 'The change in position of an object over time.' },
    { term: 'momentum', hint: 'Mass times velocity of an object in motion.' },
    { term: 'inertia', hint: 'The tendency of an object to resist changes in motion.' },
    { term: 'action', hint: 'A force applied to an object in Newton\'s third law.' },
    { term: 'reaction', hint: 'The equal and opposite force to an action.' },
    { term: 'energy', hint: 'The ability to do work or cause change.' },
    { term: 'kinetic energy', hint: 'Energy of motion, dependent on mass and velocity.' },
    { term: 'potential energy', hint: 'Stored energy due to position or configuration.' },
    { term: 'heat', hint: 'A form of energy transferred due to temperature difference.' },
    { term: 'temperature', hint: 'A measure of the average kinetic energy of particles.' },
    { term: 'thermometer', hint: 'An instrument used to measure temperature.' },
    { term: 'conduction', hint: 'Heat transfer through direct contact between materials.' },
    { term: 'convection', hint: 'Heat transfer through the movement of fluids.' },
    { term: 'radiation', hint: 'Heat transfer through electromagnetic waves.' },
    { term: 'work', hint: 'The transfer of energy when a force moves an object.' },
    { term: 'power', hint: 'The rate at which work is done or energy is transferred.' },
    { term: 'simple machine', hint: 'A basic device that changes the direction or magnitude of force.' },
    { term: 'lever', hint: 'A simple machine consisting of a rigid bar pivoted on a fulcrum.' },
    { term: 'pulley', hint: 'A simple machine using a wheel and rope to lift loads.' },
    { term: 'inclined plane', hint: 'A simple machine that is a flat surface at an angle.' },
    { term: 'wedge', hint: 'A simple machine that is a triangular tool for splitting.' },
    { term: 'screw', hint: 'An inclined plane wrapped around a cylinder.' },
    { term: 'wheel and axle', hint: 'A simple machine where a wheel is attached to a central axle.' },
    { term: 'mechanical advantage', hint: 'The ratio of output force to input force in a machine.' },
    { term: 'effort', hint: 'The force applied to a simple machine.' },
    { term: 'load', hint: 'The force or weight overcome by a simple machine.' },
    { term: 'fulcrum', hint: 'The pivot point of a lever.' },
    { term: 'sound', hint: 'Vibrations that travel through a medium as longitudinal waves.' },
    { term: 'vibration', hint: 'Rapid back-and-forth movement that produces sound.' },
    { term: 'wave', hint: 'A disturbance that transfers energy through a medium.' },
    { term: 'wavelength', hint: 'The distance between consecutive crests of a wave.' },
    { term: 'frequency', hint: 'The number of waves passing a point per second.' },
    { term: 'amplitude', hint: 'The maximum displacement of particles in a wave.' },
    { term: 'echo', hint: 'Sound reflection that allows perception of distance.' },
    { term: 'pitch', hint: 'The perceived highness or lowness of a sound, related to frequency.' },
    { term: 'resonance', hint: 'When an object vibrates at its natural frequency.' },
    { term: 'acoustics', hint: 'The science of sound and its properties.' },
    { term: 'light', hint: 'Electromagnetic radiation visible to the human eye.' },
    { term: 'reflection', hint: 'The bouncing of light off a surface.' },
    { term: 'refraction', hint: 'The bending of light as it passes between mediums.' },
    { term: 'prism', hint: 'A transparent optical element that separates white light into colors.' },
    { term: 'spectrum', hint: 'The range of colors produced when white light is dispersed.' },
    { term: 'visible light', hint: 'The portion of the electromagnetic spectrum visible to humans.' },
    { term: 'ultraviolet', hint: 'Electromagnetic radiation with wavelengths shorter than visible light.' },
    { term: 'infrared', hint: 'Electromagnetic radiation with wavelengths longer than visible light.' },
    { term: 'transparent', hint: 'Allowing light to pass through without distortion.' },
    { term: 'translucent', hint: 'Allowing some light to pass but diffusing it.' },
    { term: 'opaque', hint: 'Blocking light from passing through.' },
    { term: 'shadow', hint: 'A dark area created when an object blocks light.' },
    { term: 'lens', hint: 'A curved transparent material that refracts light.' },
    { term: 'mirror', hint: 'A surface that reflects light to form images.' },
    { term: 'optics', hint: 'The branch of physics dealing with light and vision.' },
    { term: 'color', hint: 'The visual perception of different wavelengths of light.' },
    { term: 'pigment', hint: 'A substance that absorbs specific wavelengths of light.' },
    { term: 'primary colors', hint: 'Red, yellow, and blue colors that can be mixed to make others.' },
    { term: 'secondary colors', hint: 'Colors made by mixing two primary colors.' },
    { term: 'electricity', hint: 'A form of energy resulting from the flow of electric charge.' },
    { term: 'electric charge', hint: 'A fundamental property of matter related to electrons and protons.' },
    { term: 'positive charge', hint: 'The type of charge carried by protons.' },
    { term: 'negative charge', hint: 'The type of charge carried by electrons.' },
    { term: 'neutral', hint: 'Having no net electric charge.' },
    { term: 'static electricity', hint: 'Buildup of electric charge on an object\'s surface.' },
    { term: 'current electricity', hint: 'The flow of electric charge through a conductor.' },
    { term: 'circuit', hint: 'A closed path for electric current to flow.' },
    { term: 'series circuit', hint: 'A circuit where components are connected end-to-end.' },
    { term: 'parallel circuit', hint: 'A circuit where components share two common nodes.' },
    { term: 'conductor', hint: 'A material that allows electric current to flow easily.' },
    { term: 'insulator', hint: 'A material that resists the flow of electric current.' },
    { term: 'voltage', hint: 'The electric potential difference that drives current.' },
    { term: 'amperage', hint: 'The measure of electric current in amperes.' },
    { term: 'resistance', hint: 'Opposition to the flow of electric current.' },
    { term: 'ohm', hint: 'The unit of electrical resistance.' },
    { term: 'battery', hint: 'A device that converts chemical energy to electrical energy.' },
    { term: 'terminal', hint: 'The positive or negative connection point of a battery.' },
    { term: 'switch', hint: 'A device that opens or closes an electric circuit.' },
    { term: 'electromagnet', hint: 'A magnet created by electric current in a coil.' },
    { term: 'motor', hint: 'A device that converts electrical energy to mechanical energy.' },
    { term: 'generator', hint: 'A device that converts mechanical energy to electrical energy.' },
    { term: 'transformer', hint: 'A device that changes voltage levels in AC circuits.' },
    { term: 'watt', hint: 'The unit of power in the electrical system.' },
    { term: 'kilowatt', hint: 'One thousand watts of power.' },
    { term: 'renewable energy', hint: 'Energy from sources that are naturally replenishing.' },
    { term: 'non-renewable energy', hint: 'Energy from finite sources like fossil fuels.' },
    { term: 'atom', hint: 'The smallest unit of an element that retains its properties.' },
    { term: 'electron', hint: 'A subatomic particle with negative charge orbiting the nucleus.' },
    { term: 'proton', hint: 'A subatomic particle with positive charge in the nucleus.' },
    { term: 'neutron', hint: 'A neutral subatomic particle in the atomic nucleus.' },
    { term: 'atomic number', hint: 'The number of protons in an atom\'s nucleus.' },
    { term: 'atomic mass', hint: 'The mass of an atom, approximately equal to protons plus neutrons.' },
    { term: 'element', hint: 'A pure substance made of atoms with the same atomic number.' },
    { term: 'compound', hint: 'A substance formed by chemical combination of two or more elements.' },
    { term: 'mixture', hint: 'A combination of two or more substances not chemically bonded.' },
    { term: 'solution', hint: 'A homogeneous mixture of two or more substances.' },
    { term: 'solute', hint: 'The substance that dissolves in a solvent to form a solution.' },
    { term: 'solvent', hint: 'The substance that dissolves the solute in a solution.' },
    { term: 'saturated solution', hint: 'A solution that holds the maximum amount of solute at a given temperature.' },
    { term: 'unsaturated solution', hint: 'A solution that can still dissolve more solute.' },
    { term: 'suspension', hint: 'A heterogeneous mixture with large particles that settle out.' },
    { term: 'colloid', hint: 'A mixture where particles are dispersed but not dissolved.' },
    { term: 'periodic table', hint: 'A tabular arrangement of chemical elements by atomic number.' },
    { term: 'metal', hint: 'An element that is typically shiny, conductive, and malleable.' },
    { term: 'nonmetal', hint: 'An element that is typically brittle and poor conductor.' },
    { term: 'metalloid', hint: 'An element with properties intermediate between metals and nonmetals.' },
    { term: 'acid', hint: 'A substance with pH less than 7 that donates hydrogen ions.' },
    { term: 'base', hint: 'A substance with pH greater than 7 that accepts hydrogen ions.' },
    { term: 'ph scale', hint: 'A scale from 0 to 14 measuring acidity or basicity of a solution.' },
    { term: 'indicator', hint: 'A substance that changes color in response to pH or other conditions.' },
    { term: 'oxidation', hint: 'A chemical reaction involving loss of electrons.' },
    { term: 'reduction', hint: 'A chemical reaction involving gain of electrons.' },
    { term: 'combustion', hint: 'A rapid chemical reaction between fuel and oxygen producing heat.' },
    { term: 'rust', hint: 'The oxidation of iron that forms iron oxide.' },
    { term: 'corrosion', hint: 'The gradual destruction of materials by chemical reaction with environment.' },
    { term: 'reactant', hint: 'A starting substance in a chemical reaction.' },
    { term: 'product', hint: 'A substance formed as a result of a chemical reaction.' },
    { term: 'exothermic', hint: 'A reaction that releases heat energy to the surroundings.' },
    { term: 'endothermic', hint: 'A reaction that absorbs heat energy from the surroundings.' },
    { term: 'chemical change', hint: 'A process that creates new substances with different properties.' },
    { term: 'physical change', hint: 'A process that alters form but not composition of a substance.' },
    { term: 'alloy', hint: 'A mixture of metals or metal with nonmetal.' },
    { term: 'crystal', hint: 'A solid with atoms arranged in a repeating pattern.' },
    { term: 'crystalline', hint: 'Having a crystal structure with ordered atoms.' },
    { term: 'amorphous', hint: 'Lacking a crystalline structure, like glass.' },
    { term: 'solubility', hint: 'The ability of a substance to dissolve in a solvent.' },
    { term: 'buoyancy', hint: 'The upward force exerted by a fluid on an object immersed in it.' },
    { term: 'displacement', hint: 'The volume of fluid pushed aside by an object.' },
    { term: 'pressure', hint: 'Force applied per unit area.' },
    { term: 'atmospheric pressure', hint: 'The pressure exerted by the weight of the atmosphere.' },
    { term: 'barometer', hint: 'An instrument for measuring atmospheric pressure.' },
    { term: 'vacuum', hint: 'Space completely devoid of matter.' },
    { term: 'elastic collision', hint: 'A collision where kinetic energy is conserved.' },
    { term: 'inelastic collision', hint: 'A collision where kinetic energy is not conserved.' },
    { term: 'aerodynamics', hint: 'The study of air flow around objects.' },
    { term: 'terminal velocity', hint: 'The constant speed reached when drag equals gravitational force.' },
    { term: 'free fall', hint: 'Motion under gravity alone, without air resistance.' },
    { term: 'trajectory', hint: 'The path followed by a projectile.' },
    { term: 'earth', hint: 'The third planet from the Sun and our home planet.' },
    { term: 'crust', hint: 'The outermost, thin layer of Earth\'s surface.' },
    { term: 'mantle', hint: 'The layer of Earth between the crust and core.' },
    { term: 'core', hint: 'The innermost layer of Earth, composed mostly of iron.' },
    { term: 'inner core', hint: 'The solid, central part of Earth\'s core.' },
    { term: 'outer core', hint: 'The liquid layer surrounding Earth\'s inner core.' },
    { term: 'lithosphere', hint: 'The rigid outer layer of Earth including crust and upper mantle.' },
    { term: 'asthenosphere', hint: 'The semi-fluid layer beneath the lithosphere.' },
    { term: 'mesosphere', hint: 'The layer of Earth\'s mantle below the asthenosphere.' },
    { term: 'tectonic plate', hint: 'Large pieces of the lithosphere that move on Earth\'s surface.' },
    { term: 'plate tectonics', hint: 'The theory explaining movement and interaction of tectonic plates.' },
    { term: 'convergent boundary', hint: 'Where tectonic plates move toward each other.' },
    { term: 'divergent boundary', hint: 'Where tectonic plates move away from each other.' },
    { term: 'transform boundary', hint: 'Where tectonic plates slide past each other.' },
    { term: 'continent', hint: 'A large continuous landmass on Earth\'s surface.' },
    { term: 'mountain range', hint: 'A series of mountains formed together geologically.' },
    { term: 'valley', hint: 'A low area between hills or mountains.' },
    { term: 'plateau', hint: 'A flat elevated landform rising sharply above surroundings.' },
    { term: 'canyon', hint: 'A deep valley with steep sides, often carved by a river.' },
    { term: 'ridge', hint: 'An elevated landform with sloping sides.' },
    { term: 'trench', hint: 'A long, narrow, deep depression in the ocean floor.' },
    { term: 'island', hint: 'A landmass completely surrounded by water.' },
    { term: 'peninsula', hint: 'A landmass nearly surrounded by water on three sides.' },
    { term: 'isthmus', hint: 'A narrow strip of land connecting two larger land areas.' },
    { term: 'erosion', hint: 'The process of wearing away and transport of earth materials.' },
    { term: 'weathering', hint: 'The breakdown of rocks and minerals at Earth\'s surface.' },
    { term: 'deposition', hint: 'The process where sediment is laid down by wind or water.' },
    { term: 'sediment', hint: 'Particles of rock or organic material transported and deposited.' },
    { term: 'soil', hint: 'The upper layer of earth where plants grow.' },
    { term: 'topsoil', hint: 'The uppermost, nutrient-rich layer of soil.' },
    { term: 'subsoil', hint: 'The layer beneath topsoil containing more minerals.' },
    { term: 'bedrock', hint: 'The solid rock layer beneath soil.' },
    { term: 'rock cycle', hint: 'The continuous process transforming rocks between types.' },
    { term: 'igneous rock', hint: 'Rock formed from cooled and solidified magma or lava.' },
    { term: 'sedimentary rock', hint: 'Rock formed from sediment compaction and cementation.' },
    { term: 'metamorphic rock', hint: 'Rock changed by heat, pressure, or chemical processes.' },
    { term: 'magma', hint: 'Molten rock beneath Earth\'s surface.' },
    { term: 'lava', hint: 'Molten rock that reaches Earth\'s surface.' },
    { term: 'ore', hint: 'Rock containing valuable minerals or metals.' },
    { term: 'fossil fuel', hint: 'Energy resources formed from ancient organic remains.' },
    { term: 'coal', hint: 'A fossil fuel formed from compressed plant material.' },
    { term: 'oil', hint: 'A liquid fossil fuel used for energy and plastics.' },
    { term: 'natural gas', hint: 'A gaseous fossil fuel primarily methane.' },
    { term: 'renewable resource', hint: 'A natural resource that can be replenished naturally.' },
    { term: 'non-renewable resource', hint: 'A natural resource that cannot be replenished on a human timescale.' },
    { term: 'conservation', hint: 'The protection and wise use of natural resources.' },
    { term: 'pollution', hint: 'The introduction of harmful substances into the environment.' },
    { term: 'acid rain', hint: 'Rainfall made acidic by atmospheric pollution.' },
    { term: 'greenhouse gas', hint: 'Gases that trap heat in Earth\'s atmosphere.' },
    { term: 'global warming', hint: 'The long-term rise in Earth\'s average surface temperature.' },
    { term: 'climate change', hint: 'Long-term shifts in temperature and weather patterns.' },
    { term: 'ozone layer', hint: 'A region of Earth\'s stratosphere containing protective ozone.' },
    { term: 'atmosphere', hint: 'The layer of gases surrounding Earth.' },
    { term: 'troposphere', hint: 'The lowest layer of the atmosphere where weather occurs.' },
    { term: 'stratosphere', hint: 'The layer above the troposphere containing the ozone layer.' },
    { term: 'thermosphere', hint: 'A layer of the atmosphere where auroras occur.' },
    { term: 'exosphere', hint: 'The outermost layer of Earth\'s atmosphere.' },
    { term: 'air pressure', hint: 'The force exerted by air molecules on a surface.' },
    { term: 'wind', hint: 'The movement of air from high to low pressure areas.' },
    { term: 'jet stream', hint: 'Fast-moving air currents in the upper atmosphere.' },
    { term: 'humidity', hint: 'The amount of water vapor in the air.' },
    { term: 'dew point', hint: 'The temperature at which air becomes saturated with water vapor.' },
    { term: 'cloud', hint: 'A visible mass of water droplets or ice crystals in the atmosphere.' },
    { term: 'precipitation', hint: 'Water falling from the atmosphere to Earth\'s surface.' },
    { term: 'rain', hint: 'Liquid precipitation in the form of drops.' },
    { term: 'snow', hint: 'Precipitation in the form of ice crystals.' },
    { term: 'sleet', hint: 'Precipitation of partially frozen raindrops.' },
    { term: 'hail', hint: 'Precipitation of layered ice particles formed in thunderstorms.' },
    { term: 'frost', hint: 'Ice crystals formed by deposition on cold surfaces.' },
    { term: 'dew', hint: 'Water droplets formed by condensation on cool surfaces.' },
    { term: 'weather', hint: 'The short-term state of the atmosphere in a given area.' },
    { term: 'climate', hint: 'The long-term average weather patterns in a region.' },
    { term: 'front', hint: 'The boundary between two air masses of different temperatures.' },
    { term: 'cold front', hint: 'A front where cold air advances under warm air.' },
    { term: 'warm front', hint: 'A front where warm air advances over cold air.' },
    { term: 'stationary front', hint: 'A front where air masses are not moving significantly.' },
    { term: 'occluded front', hint: 'A front where warm air is trapped between two cold air masses.' },
    { term: 'low pressure', hint: 'An area where air pressure is lower than surroundings, often bringing storms.' },
    { term: 'high pressure', hint: 'An area where air pressure is higher than surroundings, often bringing clear weather.' },
    { term: 'cyclone', hint: 'A large-scale low-pressure system rotating counterclockwise in the north.' },
    { term: 'anticyclone', hint: 'A large-scale high-pressure system rotating clockwise in the north.' },
    { term: 'tornado', hint: 'A violent rotating column of air extending from a thunderstorm.' },
    { term: 'thunderstorm', hint: 'A storm with thunder, lightning, heavy rain, and sometimes hail.' },
    { term: 'hurricane', hint: 'A tropical cyclone with sustained winds over 74 mph.' },
    { term: 'typhoon', hint: 'A hurricane occurring in the northwestern Pacific Ocean.' },
    { term: 'blizzard', hint: 'A severe snowstorm with strong winds and low visibility.' },
    { term: 'fog', hint: 'A cloud at ground level causing reduced visibility.' },
    { term: 'microclimate', hint: 'A localized climate differing from the surrounding area.' },
    { term: 'bioclimate', hint: 'The climate conditions affecting living organisms.' },
    { term: 'season', hint: 'One of four periods of the year with distinct weather patterns.' },
    { term: 'solstice', hint: 'The time when the sun reaches its highest or lowest point in the sky.' },
    { term: 'equinox', hint: 'The time when day and night are approximately equal in length.' },
    { term: 'hydrosphere', hint: 'All the water on Earth\'s surface, including oceans and groundwater.' },
    { term: 'groundwater', hint: 'Water located beneath Earth\'s surface in soil and rock.' },
    { term: 'aquifer', hint: 'An underground layer of water-bearing permeable rock.' },
    { term: 'wellspring', hint: 'A natural source where groundwater emerges.' },
    { term: 'spring', hint: 'A point where groundwater flows to the surface.' },
    { term: 'tributary', hint: 'A stream or river flowing into a larger river.' },
    { term: 'watershed', hint: 'An area of land draining into a specific body of water.' },
    { term: 'delta', hint: 'A landform at a river mouth formed by sediment deposition.' },
    { term: 'estuary', hint: 'A partially enclosed coastal body of water with brackish water.' },
    { term: 'sediment load', hint: 'The amount of sediment carried by a river.' },
    { term: 'discharge', hint: 'The volume of water flowing past a point per unit time.' },
    { term: 'flood plain', hint: 'Flat land adjacent to a river subject to flooding.' },
    { term: 'meander', hint: 'A winding curve or bend in a river.' },
    { term: 'oxbow lake', hint: 'A U-shaped lake formed when a meander is cut off.' },
    { term: 'stalactite', hint: 'An icicle-shaped mineral deposit hanging from a cave ceiling.' },
    { term: 'stalagmite', hint: 'A mineral deposit rising from a cave floor.' },
    { term: 'sinkhole', hint: 'A depression in the ground caused by collapse of surface rock.' },
    { term: 'glacier', hint: 'A large, slow-moving mass of ice.' },
    { term: 'moraine', hint: 'Rocks and debris deposited by a glacier.' },
    { term: 'lateral moraine', hint: 'Debris along the sides of a glacier.' },
    { term: 'terminal moraine', hint: 'Debris at the end of a glacier.' },
    { term: 'drumlin', hint: 'An elongated hill formed by glacial ice.' },
    { term: 'esker', hint: 'A long, winding ridge of sediment deposited by meltwater.' },
    { term: 'outwash plain', hint: 'A flat area formed by glacial sediment deposits.' },
    { term: 'sea level', hint: 'The average level of the ocean\'s surface.' },
    { term: 'tide', hint: 'The regular rise and fall of sea level caused by gravitational forces.' },
    { term: 'tidal range', hint: 'The difference in height between high and low tide.' },
    { term: 'spring tide', hint: 'A tide with the greatest difference between high and low.' },
    { term: 'neap tide', hint: 'A tide with the least difference between high and low.' },
    { term: 'current', hint: 'The flow of water in a specific direction in oceans or rivers.' },
    { term: 'turbidity current', hint: 'A fast-moving underwater current of dense sediment.' },
    { term: 'tsunami', hint: 'A series of ocean waves caused by underwater earthquakes.' },
    { term: 'earthquake', hint: 'Sudden shaking of the ground caused by tectonic movement.' },
    { term: 'epicenter', hint: 'The point on Earth\'s surface directly above an earthquake\'s focus.' },
    { term: 'hypocenter', hint: 'The underground point where an earthquake originates.' },
    { term: 'seismic wave', hint: 'Waves of energy generated by earthquakes.' },
    { term: 'surface wave', hint: 'Seismic waves traveling along Earth\'s surface.' },
    { term: 'seismograph', hint: 'An instrument that records earthquake activity.' },
    { term: 'richter scale', hint: 'A scale measuring the magnitude of earthquakes.' },
    { term: 'mercalli scale', hint: 'A scale measuring the intensity of earthquake effects.' },
    { term: 'aftershock', hint: 'A smaller earthquake following a larger one.' },
    { term: 'foreshock', hint: 'A smaller earthquake preceding a larger one.' },
    { term: 'volcano', hint: 'An opening in Earth\'s crust through which lava erupts.' },
    { term: 'caldera', hint: 'A large depression formed when a volcano collapses.' },
    { term: 'lava flow', hint: 'The movement of molten lava from a volcano.' },
    { term: 'pyroclastic flow', hint: 'A fast-moving current of hot gas and volcanic matter.' },
    { term: 'ash cloud', hint: 'A cloud of volcanic ash and gas from an eruption.' },
    { term: 'cinder cone', hint: 'A steep volcano built from loose volcanic fragments.' },
    { term: 'shield volcano', hint: 'A broad volcano with gently sloping sides from fluid lava.' },
    { term: 'stratovolcano', hint: 'A tall, cone-shaped volcano with layered lava and ash.' },
    { term: 'hot spot', hint: 'A region of magma beneath tectonic plates causing volcanism.' },
    { term: 'geyser', hint: 'A hot spring that erupts periodically with steam and water.' },
    { term: 'hot spring', hint: 'A natural spring of warm or hot groundwater.' },
    { term: 'fumarole', hint: 'A vent emitting volcanic gases and steam.' },
    { term: 'sun', hint: 'The star at the center of our solar system.' },
    { term: 'moon', hint: 'Earth\'s natural satellite that orbits the planet.' },
    { term: 'planet', hint: 'A celestial body orbiting a star with sufficient mass to be round.' },
    { term: 'star', hint: 'A massive, luminous sphere of plasma held together by gravity.' },
    { term: 'solar system', hint: 'The sun and all objects gravitationally bound to it.' },
    { term: 'galaxy', hint: 'A gravitationally bound system of stars, gas, and dust.' },
    { term: 'universe', hint: 'All existing matter, energy, and space.' },
    { term: 'milky way', hint: 'The galaxy containing our solar system.' },
    { term: 'andromeda', hint: 'The nearest major galaxy to the Milky Way.' },
    { term: 'nebula', hint: 'A cloud of gas and dust in space, often where stars form.' },
    { term: 'supernova', hint: 'The explosive death of a massive star.' },
    { term: 'black hole', hint: 'A region of spacetime with gravity so strong nothing escapes.' },
    { term: 'pulsar', hint: 'A rapidly rotating neutron star emitting beams of radiation.' },
    { term: 'quasar', hint: 'An extremely luminous active galactic nucleus.' },
    { term: 'meteor', hint: 'A small rocky or metallic body burning up in Earth\'s atmosphere.' },
    { term: 'meteorite', hint: 'A meteor that survives passage through the atmosphere.' },
    { term: 'asteroid', hint: 'A rocky object orbiting the sun, mostly in the asteroid belt.' },
    { term: 'comet', hint: 'A small icy body with a tail when approaching the sun.' },
    { term: 'orbit', hint: 'The gravitationally curved path of an object around another.' },
    { term: 'revolution', hint: 'The orbital motion of a planet around the sun.' },
    { term: 'rotation', hint: 'The spinning motion of a planet on its axis.' },
    { term: 'axis', hint: 'An imaginary line around which a planet rotates.' },
    { term: 'inclination', hint: 'The angle of a planet\'s orbit relative to Earth\'s orbit.' },
    { term: 'eccentricity', hint: 'The measure of how much an orbit deviates from a circle.' },
    { term: 'aphelion', hint: 'The point in orbit farthest from the sun.' },
    { term: 'perihelion', hint: 'The point in orbit closest to the sun.' },
    { term: 'lunar eclipse', hint: 'When Earth passes between the sun and moon, casting a shadow.' },
    { term: 'solar eclipse', hint: 'When the moon passes between Earth and sun, blocking sunlight.' },
    { term: 'penumbra', hint: 'The partial shadow region during an eclipse.' },
    { term: 'umbra', hint: 'The fully dark central shadow during an eclipse.' },
    { term: 'phase', hint: 'The changing appearance of the moon as seen from Earth.' },
    { term: 'new moon', hint: 'The phase when the moon is between Earth and sun, invisible.' },
    { term: 'full moon', hint: 'The phase when the entire face of the moon is illuminated.' },
    { term: 'crescent moon', hint: 'A thin curved illuminated section of the moon.' },
    { term: 'gibbous moon', hint: 'The phase when more than half but less than full illumination.' },
    { term: 'constellation', hint: 'A group of stars forming a recognizable pattern.' },
    { term: 'zodiac', hint: 'An area of the sky encompassing twelve constellations.' },
    { term: 'polaris', hint: 'The North Star, currently the brightest star in Ursa Minor.' },
    { term: 'light-year', hint: 'The distance light travels in one year, about 5.88 trillion miles.' },
    { term: 'astronomy', hint: 'The scientific study of celestial objects and phenomena.' },
    { term: 'astrology', hint: 'A belief system linking celestial positions to human events.' },
    { term: 'parallax', hint: 'The apparent shift of nearby stars against distant background.' },
    { term: 'redshift', hint: 'The lengthening of light wavelengths as objects move away.' },
    { term: 'blueshift', hint: 'The shortening of light wavelengths as objects move closer.' },
    { term: 'cosmic radiation', hint: 'High-energy particles from outer space.' },
    { term: 'ph', hint: 'A measure of acidity or basicity on a scale from 0 to 14.' },
    { term: 'bubble', hint: 'A thin sphere of liquid enclosing gas.' },
    { term: 'machine', hint: 'A device that transmits or modifies force or motion.' },
    { term: 'gear', hint: 'A rotating wheel with teeth to transmit motion.' },
    { term: 'pendulum', hint: 'A weight suspended to swing freely under gravity.' },
    { term: 'drought', hint: 'A prolonged period of abnormally low rainfall.' },
    { term: 'flood', hint: 'An overflow of water submerging normally dry land.' },
    { term: 'avalanche', hint: 'A rapid flow of snow down a slope.' },
    { term: 'landslide', hint: 'The sliding movement of rock and soil down a slope.' },
    { term: 'gemstone', hint: 'A mineral crystal used in jewelry for its beauty.' },
    { term: 'fault', hint: 'A fracture in Earth\'s crust where tectonic movement occurs.' },
    { term: 'earth\'s layers', hint: 'The distinct regions of Earth\'s interior from crust to core.' },
    { term: 'ocean current', hint: 'A continuous flow of seawater in a specific direction.' },
    { term: 'plankton', hint: 'Microscopic organisms drifting in water, base of aquatic food chains.' },
    { term: 'parasite', hint: 'An organism living on or in a host, harming it.' },
    { term: 'host', hint: 'An organism that harbors a parasite or pathogen.' },
    { term: 'niche', hint: 'The role and position a species occupies in its environment.' },
    { term: 'extinction', hint: 'The complete dying out of a species.' },
    { term: 'fossil record', hint: 'The history of life documented by fossils.' },
    { term: 'dinosaur', hint: 'Extinct reptiles that dominated Earth for 165 million years.' },
    { term: 'ice age', hint: 'A period of long-term cooling with extensive ice sheets.' },
    { term: 'inherit', hint: 'To receive genetic traits from parents.' },
    { term: 'selective breeding', hint: 'Breeding organisms with desired traits to produce offspring with those traits.' },
    { term: 'clone', hint: 'A genetically identical copy of an organism.' },
    { term: 'microscope', hint: 'An instrument that magnifies small objects.' },
    { term: 'cell membrane', hint: 'A thin layer surrounding the cell, controlling what enters and exits.' },
    { term: 'cytoplasm', hint: 'The jelly-like substance inside the cell membrane.' },
    { term: 'organelle', hint: 'A specialized structure within a cell performing specific functions.' },
    { term: 'vacuole', hint: 'A membrane-bound organelle storing water and nutrients in cells.' },
    { term: 'unicellular', hint: 'An organism consisting of a single cell.' },
    { term: 'multicellular', hint: 'An organism composed of many specialized cells.' },
    { term: 'spore', hint: 'A reproductive structure resistant to unfavorable conditions.' },
    { term: 'lichen', hint: 'A symbiotic partnership between fungi and algae or cyanobacteria.' },
    { term: 'moss', hint: 'A small, non-vascular plant that grows in damp areas.' },
    { term: 'fern', hint: 'A vascular plant that reproduces by spores, lacking seeds.' },
    { term: 'conifer', hint: 'A gymnosperm with needle-like leaves and cones.' },
    { term: 'angiosperm', hint: 'A flowering plant with seeds enclosed in fruit.' },
    { term: 'gymnosperm', hint: 'A seed plant with naked seeds not enclosed in fruit.' },
    { term: 'seed dispersal', hint: 'The scattering of seeds away from the parent plant.' },
    { term: 'tropism', hint: 'The growth movement of plants in response to stimuli.' },
    { term: 'root hair', hint: 'A tiny extension of root cells that increases absorption.' },
    { term: 'xylem', hint: 'Plant tissue that transports water and minerals upward.' },
    { term: 'phloem', hint: 'Plant tissue that transports sugars from leaves to other parts.' },
    { term: 'carnivorous plant', hint: 'A plant that traps and digests insects or small animals.' },
    { term: 'fermentation', hint: 'A metabolic process converting sugar to acids, gases, or alcohol.' },
    { term: 'calorie', hint: 'A unit of energy, especially heat or food energy.' },
    { term: 'metabolism', hint: 'The chemical processes that sustain life in organisms.' },
    { term: 'excretion', hint: 'The process of removing waste products from the body.' },
    { term: 'homeostasis', hint: 'The maintenance of stable internal conditions in an organism.' },
    { term: 'stimulus', hint: 'A change in the environment detected by an organism.' },
    { term: 'response', hint: 'An organism\'s reaction to a stimulus.' },
    { term: 'neuron', hint: 'A nerve cell that transmits electrical impulses.' },
    { term: 'synapse', hint: 'The junction between two nerve cells where signals are transmitted.' },
    { term: 'endocrine system', hint: 'The system of glands secreting hormones into the bloodstream.' },
    { term: 'antibody', hint: 'A protein produced by the immune system to neutralize pathogens.' },
    { term: 'pathogen', hint: 'A microorganism that causes disease.' },
    { term: 'epidemic', hint: 'A rapid spread of disease affecting many in a community.' },
    { term: 'pandemic', hint: 'An epidemic spreading over multiple countries or continents.' },
    { term: 'vaccination', hint: 'The administration of a vaccine to produce immunity.' },
    { term: 'antiseptic', hint: 'A substance that prevents growth of disease-causing microorganisms.' },
    { term: 'sterilize', hint: 'To eliminate all microorganisms from an object or surface.' },
    { term: 'microbe', hint: 'A microscopic organism, especially bacteria or virus.' },
    { term: 'antibacterial', hint: 'A substance that kills or inhibits bacteria.' },
    { term: 'protozoa', hint: 'Single-celled eukaryotic microorganisms.' },
    { term: 'immune', hint: 'Protected against a particular disease.' },
    { term: 'allergy', hint: 'An immune response to a harmless substance.' },
    { term: 'toxin', hint: 'A poisonous substance produced by living organisms.' },
    { term: 'absorption', hint: 'The process by which nutrients enter the bloodstream.' },
    { term: 'circulation', hint: 'The transport of blood through the body.' },
    { term: 'pulse', hint: 'The rhythmic expansion of arteries from heartbeats.' },
    { term: 'blood pressure', hint: 'The force of blood against artery walls.' },
    { term: 'hemoglobin', hint: 'A protein in red blood cells that carries oxygen.' },
    { term: 'platelet', hint: 'A blood cell fragment involved in clotting.' },
    { term: 'white blood cell', hint: 'A cell of the immune system fighting infection.' },
    { term: 'red blood cell', hint: 'A cell that transports oxygen via hemoglobin.' },
    { term: 'lymph', hint: 'A fluid containing white blood cells that helps immunity.' },
    { term: 'bone marrow', hint: 'Soft tissue inside bones producing blood cells.' },
    { term: 'cartilage', hint: 'Flexible connective tissue cushioning joints.' },
    { term: 'joint', hint: 'The point where two bones meet, allowing movement.' },
    { term: 'nervous system', hint: 'The system controlling body activities through electrical signals.' },
    { term: 'brainstem', hint: 'The part of the brain connecting to the spinal cord.' },
    { term: 'cerebellum', hint: 'The brain region coordinating movement and balance.' },
    { term: 'cerebrum', hint: 'The largest brain part handling higher functions like thought.' },
    { term: 'spinal cord', hint: 'A bundle of nerves transmitting signals between brain and body.' },
    { term: 'sensory organ', hint: 'A structure detecting external stimuli like eyes or ears.' },
    { term: 'pupil', hint: 'The opening in the eye that allows light to enter.' },
    { term: 'retina', hint: 'The light-sensitive layer at the back of the eye.' },
    { term: 'cochlea', hint: 'A spiral structure in the ear converting sound to nerve signals.' },
    { term: 'eustachian tube', hint: 'A tube connecting the middle ear to the throat for pressure equalization.' },
    { term: 'olfactory', hint: 'Related to the sense of smell.' },
    { term: 'taste bud', hint: 'A sensory structure on the tongue detecting flavors.' },
    { term: 'hair follicle', hint: 'A structure in the skin from which hair grows.' },
    { term: 'sweat gland', hint: 'A gland that produces sweat to regulate body temperature.' },
    { term: 'melanin', hint: 'A pigment giving color to skin, hair, and eyes.' },
    { term: 'uv light', hint: 'Ultraviolet radiation from the sun that can cause skin damage.' },
    { term: 'suntan', hint: 'Darkening of skin from UV exposure as protection.' },
    { term: 'burn', hint: 'Damage to skin from excessive heat or UV radiation.' },
    { term: 'blister', hint: 'A fluid-filled pocket in the skin from burns or friction.' },
    { term: 'scar', hint: 'Fibrous tissue replacing normal skin after injury.' },
    { term: 'allergens', hint: 'Substances that cause allergic reactions in sensitive individuals.' },
    { term: 'asthma', hint: 'A respiratory condition causing difficulty breathing.' },
    { term: 'diabetes', hint: 'A disease affecting blood sugar regulation.' },
    { term: 'obesity', hint: 'Excess body fat accumulation posing health risks.' },
    { term: 'malnutrition', hint: 'Poor nutrition from inadequate or imbalanced diet.' },
    { term: 'hydration', hint: 'The process of providing adequate water to the body.' },
    { term: 'dehydration', hint: 'Excessive loss of body water leading to health issues.' },
    { term: 'electrolyte', hint: 'Minerals in body fluids conducting electrical impulses.' },
    { term: 'ph balance', hint: 'Maintaining the body\'s optimal acid-base equilibrium.' },
    { term: 'thermoregulation', hint: 'The process of maintaining body temperature within limits.' },
    { term: 'shivering', hint: 'Involuntary muscle contractions generating heat.' },
    { term: 'sweating', hint: 'The release of water and salt from glands to cool the body.' },
    { term: 'goosebumps', hint: 'Small bumps on skin from cold or emotion, raising hairs.' },
    { term: 'adrenaline', hint: 'A hormone triggering the fight-or-flight response.' },
    { term: 'stress', hint: 'The body\'s response to challenging or threatening situations.' },
    { term: 'sleep', hint: 'A state of reduced consciousness for rest and recovery.' },
    { term: 'dream', hint: 'A series of thoughts and images during sleep.' },
    { term: 'rem sleep', hint: 'Rapid eye movement sleep stage associated with dreaming.' },
    { term: 'circadian rhythm', hint: 'The body\'s internal 24-hour cycle regulating sleep and activity.' },
    { term: 'jet lag', hint: 'Disruption of circadian rhythm from rapid time zone changes.' },
    { term: 'hypothermia', hint: 'Dangerously low body temperature from cold exposure.' },
    { term: 'heatstroke', hint: 'A severe heat-related illness from body temperature regulation failure.' },
    { term: 'frostbite', hint: 'Tissue damage from freezing temperatures.' },
    { term: 'first aid', hint: 'Initial emergency care given to injured or ill persons.' },
    { term: 'cpr', hint: 'Cardiopulmonary resuscitation to restore breathing and circulation.' },
    { term: 'bandage', hint: 'A strip of material to cover and protect wounds.' },
    { term: 'disinfectant', hint: 'A chemical agent destroying microorganisms on surfaces.' },
    { term: 'sterilization', hint: 'The complete elimination of all forms of microbial life.' },
    { term: 'quarantine', hint: 'Isolation of individuals exposed to contagious disease.' },
    { term: 'outbreak', hint: 'A sudden increase in disease cases in a specific area.' },
    { term: 'contagious', hint: 'Capable of being transmitted from one person to another.' },
    { term: 'incubation', hint: 'The period between exposure to a pathogen and symptom appearance.' },
    { term: 'symptom', hint: 'A change indicating the presence of a disease or condition.' },
    { term: 'diagnosis', hint: 'The identification of a disease through examination.' },
    { term: 'treatment', hint: 'Medical care provided to improve health or relieve symptoms.' },
    { term: 'cure', hint: 'A remedy that eliminates a disease completely.' },
    { term: 'prevention', hint: 'Actions taken to avoid the occurrence of disease.' },
    { term: 'hygiene', hint: 'Practices promoting health through cleanliness.' },
    { term: 'sanitation', hint: 'Conditions relating to public health, especially sewage disposal.' },
    { term: 'waste management', hint: 'The collection, transport, and disposal of waste materials.' },
    { term: 'recycling', hint: 'Processing used materials into new products.' },
    { term: 'sustainability', hint: 'Using resources to meet needs without compromising future generations.' },
    { term: 'green energy', hint: 'Energy from renewable sources with low environmental impact.' },
    { term: 'technology', hint: 'The application of scientific knowledge for practical purposes.' },
    { term: 'invention', hint: 'A new device or process created through design and ingenuity.' },
    { term: 'robot', hint: 'A machine programmed to carry out complex actions automatically.' },
    { term: 'computer', hint: 'An electronic device processing and storing data.' },
    { term: 'internet', hint: 'A global network connecting computers for information exchange.' },
    { term: 'program', hint: 'A set of instructions for a computer to perform tasks.' },
    { term: 'code', hint: 'Instructions written in a programming language.' },
    { term: 'algorithm', hint: 'A step-by-step procedure for solving a problem.' },
    { term: 'design', hint: 'The planning and creation of a product or system.' },
    { term: 'prototyping', hint: 'Creating a preliminary model to test a design.' },
    { term: 'bridge', hint: 'A structure carrying a road or path over an obstacle.' },
    { term: 'tower', hint: 'A tall structure used for support or observation.' },
    { term: 'structure', hint: 'Something constructed from organized parts.' },
    { term: 'stability', hint: 'The ability of a structure to resist collapse or unwanted movement.' },
    { term: 'tool', hint: 'An implement used to carry out a particular function.' },
    { term: 'measurement', hint: 'The process of determining the size, length, or amount of something.' },
    { term: 'ruler', hint: 'A straight strip used to measure length.' },
    { term: 'balance scale', hint: 'A device comparing weights on two pans.' },
    { term: 'observation', hint: 'The act of noting and recording facts or events.' },
    { term: 'hypothesis', hint: 'A proposed explanation for a phenomenon, testable by experiment.' },
    { term: 'experiment', hint: 'A procedure to test a hypothesis under controlled conditions.' },
    { term: 'prediction', hint: 'A statement about what will happen in an experiment.' },
    { term: 'data', hint: 'Information collected from observations or experiments.' },
    { term: 'conclusion', hint: 'A judgment based on evidence from an experiment.' },
    { term: 'variable', hint: 'A factor that can change or vary in an experiment.' },
    { term: 'control', hint: 'The standard for comparison in an experiment.' },
    { term: 'measure', hint: 'To determine the extent, dimensions, or quantity of something.' },
    { term: 'compare', hint: 'To examine similarities and differences between things.' },
    { term: 'classify', hint: 'To arrange items into groups based on shared characteristics.' },
    { term: 'pattern', hint: 'A regular or repetitive arrangement of data or events.' },
    { term: 'model', hint: 'A simplified representation of a system or process.' },
    { term: 'evidence', hint: 'Data or information supporting a conclusion.' },
    { term: 'inquiry', hint: 'The process of asking questions and seeking answers.' },
    { term: 'scientist', hint: 'A person who systematically studies nature through observation and experiment.' },
    { term: 'laboratory', hint: 'A facility equipped for scientific research and experiments.' },
    { term: 'magnifying glass', hint: 'A convex lens used to enlarge the apparent size of objects.' },
    { term: 'telescope', hint: 'An optical instrument for viewing distant objects.' },
    { term: 'plants', hint: 'Multicellular organisms that produce food through photosynthesis.' },
    { term: 'petal', hint: 'A modified leaf in a flower attracting pollinators.' },
    { term: 'pollen', hint: 'Fine powder containing male gametes in seed plants.' },
    { term: 'chlorophyll', hint: 'A green pigment in plants essential for photosynthesis.' },
    { term: 'oxygen', hint: 'A gas essential for respiration in most living organisms.' },
    { term: 'carbon dioxide', hint: 'A gas used by plants in photosynthesis and produced in respiration.' },
    { term: 'tree', hint: 'A tall perennial plant with a single woody stem (trunk).' },
    { term: 'bark', hint: 'The outer protective layer of a tree\'s stem and roots.' },
    { term: 'sap', hint: 'The fluid tissue transporting nutrients in plants.' },
    { term: 'evergreen', hint: 'A plant that retains green leaves throughout the year.' },
    { term: 'deciduous', hint: 'A tree that sheds its leaves annually.' },
    { term: 'mammal', hint: 'A warm-blooded vertebrate with hair and mammary glands.' },
    { term: 'reptile', hint: 'A cold-blooded vertebrate with scaly skin.' },
    { term: 'amphibian', hint: 'A vertebrate living both in water and on land, like frogs.' },
    { term: 'bird', hint: 'A warm-blooded vertebrate with feathers and wings.' },
    { term: 'fish', hint: 'A cold-blooded aquatic vertebrate with gills.' },
    { term: 'insect', hint: 'A small arthropod with six legs and a three-part body.' },
    { term: 'arachnid', hint: 'An arthropod with eight legs, like spiders and scorpions.' },
    { term: 'vertebrate', hint: 'An animal with a backbone or spinal column.' },
    { term: 'invertebrate', hint: 'An animal without a backbone.' },
    { term: 'tissue', hint: 'A group of similar cells performing a specific function.' },
    { term: 'organ', hint: 'A structure of different tissues working together.' },
    { term: 'lungs', hint: 'Paired organs in the chest for gas exchange.' },
    { term: 'bones', hint: 'Rigid organs providing structure and protection.' },
    { term: 'muscles', hint: 'Contractile tissues producing movement.' },
    { term: 'skin', hint: 'The outer protective covering of the body.' },
    { term: 'digestive system', hint: 'The organs breaking down food for nutrient absorption.' },
    { term: 'respiratory system', hint: 'The organs facilitating gas exchange with the environment.' },
    { term: 'circulatory system', hint: 'The system transporting blood, oxygen, and nutrients.' },
    { term: 'nutrition', hint: 'The process of obtaining and using food for energy and growth.' },
    { term: 'growth', hint: 'The increase in size or number of cells in an organism.' },
    { term: 'life cycle', hint: 'The stages an organism goes through from birth to reproduction.' },
    { term: 'egg', hint: 'A reproductive cell or structure containing an embryo.' },
    { term: 'germs', hint: 'Microorganisms, especially those causing disease.' },
    { term: 'disease', hint: 'An abnormal condition affecting the body or mind.' },
    { term: 'vaccine', hint: 'A biological preparation stimulating immunity to a disease.' },
    { term: 'immune system', hint: 'The body\'s defense against disease-causing agents.' },
    { term: 'antibiotics', hint: 'Medications killing or inhibiting bacteria growth.' },
    { term: 'fungi', hint: 'A kingdom of organisms including yeasts and mushrooms.' },
    { term: 'rock', hint: 'A natural solid aggregate of minerals.' },
    { term: 'mountain', hint: 'A large landform rising abruptly above surroundings.' },
    { term: 'river', hint: 'A natural flowing watercourse toward an ocean or sea.' },
    { term: 'lake', hint: 'A large body of water surrounded by land.' },
    { term: 'landform', hint: 'A natural feature of Earth\'s surface.' },
    { term: 'storm', hint: 'Disturbance in the atmosphere with strong winds and precipitation.' },
    { term: 'thunder', hint: 'The sound caused by rapid expansion of air around lightning.' },
    { term: 'lightning', hint: 'A massive electrical discharge during a thunderstorm.' },
    { term: 'forecast', hint: 'A prediction of future weather conditions.' },
    { term: 'mercury', hint: 'The planet closest to the Sun.' },
    { term: 'venus', hint: 'The second planet from the Sun, Earth\'s closest neighbor.' },
    { term: 'mars', hint: 'The fourth planet, known as the Red Planet.' },
    { term: 'jupiter', hint: 'The largest planet in the solar system.' },
    { term: 'saturn', hint: 'The sixth planet, known for its prominent rings.' },
    { term: 'uranus', hint: 'The seventh planet, an ice giant tilted on its side.' },
    { term: 'neptune', hint: 'The eighth planet, a deep blue ice giant.' },
    { term: 'pluto', hint: 'A dwarf planet beyond Neptune\'s orbit.' },
    { term: 'astronaut', hint: 'A person trained to travel and work in space.' },
    { term: 'space shuttle', hint: 'A reusable spacecraft for transporting cargo and crew.' },
    { term: 'satellite', hint: 'An object orbiting a planet, either natural or artificial.' },
    { term: 'eclipse', hint: 'The obscuring of one celestial body by another.' },
    { term: 'crater', hint: 'A bowl-shaped depression on a celestial body from impact.' },
    { term: 'molecule', hint: 'Two or more atoms bonded together.' },
    { term: 'float', hint: 'To rest on the surface of a liquid due to buoyancy.' },
    { term: 'sink', hint: 'To descend below the surface of a liquid due to density.' },
    { term: 'condensing', hint: 'Changing from gas to liquid state.' },
    { term: 'evaporating', hint: 'Changing from liquid to gas state.' },
    { term: 'dissolve', hint: 'To mix a solute into a solvent to form a solution.' },
    { term: 'filter', hint: 'To separate solids from liquids or gases using a porous material.' },
    { term: 'magnetic', hint: 'Having the properties of a magnet, attracting iron.' },
    { term: 'conduct', hint: 'To transmit heat, electricity, or sound.' },
    { term: 'insulate', hint: 'To prevent the passage of heat, electricity, or sound.' },
    { term: 'absorb', hint: 'To take in or soak up energy, liquid, or other substance.' },
    { term: 'bulb', hint: 'The glass component of a light fixture containing a filament.' },
    { term: 'push', hint: 'To exert force away from oneself.' },
    { term: 'pull', hint: 'To exert force toward oneself.' },
    { term: 'balance', hint: 'Stability achieved when forces are equal.' },
    { term: 'environment', hint: 'The surroundings or conditions influencing organisms.' },
    { term: 'recycle', hint: 'To process waste materials for reuse.' },
    { term: 'reuse', hint: 'To use something again for its original or another purpose.' },
    { term: 'reduce', hint: 'To decrease the amount of waste or resource consumption.' },
    { term: 'compost', hint: 'To decompose organic waste into nutrient-rich soil.' },
    { term: 'natural resource', hint: 'Materials from nature used by humans.' },
    { term: 'renewable', hint: 'Able to be replenished naturally over short periods.' },
    { term: 'non-renewable', hint: 'Unable to be replenished on a human timescale.' },
    { term: 'solar energy', hint: 'Energy derived from the sun\'s radiation.' },
    { term: 'wind energy', hint: 'Energy harnessed from wind using turbines.' },
    { term: 'water conservation', hint: 'The careful use and protection of water resources.' },
    { term: 'endangered species', hint: 'A species at risk of extinction.' },
    { term: 'deforestation', hint: 'The clearing of forests on a large scale.' },
    { term: 'carbon footprint', hint: 'The total greenhouse gas emissions caused by an individual or entity.' }
];

    function chooseNewTerm() {
        const randomIndex = Math.floor(Math.random() * scientificTerms.length);
        return scientificTerms[randomIndex];
    }

    function scrambleTerm(term) {
        return term.split('').sort(() => Math.random() - 0.5).join('');
    }

    function initializeGame() {
        currentTerm = chooseNewTerm();
        const scrambled = scrambleTerm(currentTerm.term);

        scrambledLettersContainer.innerHTML = '';
        dropZone.innerHTML = '';
        feedback.textContent = '';
        hintText.textContent = `Hint: ${currentTerm.hint}`;

        scrambled.split('').forEach(letter => {
            const tile = document.createElement('div');
            tile.textContent = letter;
            tile.classList.add('letter-tile');
            tile.setAttribute('draggable', 'true');
            scrambledLettersContainer.appendChild(tile);
        });

        addDragAndDropListeners();
    }

    function addDragAndDropListeners() {
        const tiles = document.querySelectorAll('.letter-tile');

        tiles.forEach(tile => {
            tile.addEventListener('dragstart', handleDragStart);
            tile.addEventListener('dragend', handleDragEnd);
        });

        dropZone.addEventListener('dragover', handleDragOver);
        dropZone.addEventListener('drop', handleDrop);
        scrambledLettersContainer.addEventListener('dragover', handleDragOver);
        scrambledLettersContainer.addEventListener('drop', handleDrop);
    }

    function handleDragStart(e) {
        draggedTile = e.target;
        setTimeout(() => {
            e.target.classList.add('dragging');
        }, 0);
    }

    function handleDragEnd(e) {
        e.target.classList.remove('dragging');
    }

    function handleDragOver(e) {
        e.preventDefault();
    }

    function handleDrop(e) {
        e.preventDefault();
        const dropContainer = e.target.closest('.letter-container, .drop-zone');
        if (dropContainer && draggedTile) {
            dropContainer.appendChild(draggedTile);
        }
    }

    function checkAnswer() {
        const droppedLetters = [...dropZone.children].map(tile => tile.textContent).join('');
        if (droppedLetters === currentTerm.term) {
            feedback.textContent = 'Correct! Well done!';
            feedback.style.color = 'green';
            score++;
            scoreDisplay.textContent = score;
        } else {
            feedback.textContent = 'Not quite, try again!';
            feedback.style.color = 'red';
        }
    }

    function startGame() {
        startContainer.classList.add('hidden');
        gameContainer.classList.remove('hidden');
        initializeGame();
    }

    function resetGame() {
        score = 0;
        scoreDisplay.textContent = score;
        startGame();
    }

    checkBtn.addEventListener('click', checkAnswer);
    nextBtn.addEventListener('click', initializeGame);
    startBtn.addEventListener('click', startGame);
    resetBtn.addEventListener('click', resetGame);
});